### ISSUE TITLE
Migrate Issues and Docs to GitHub

### ISSUE THREAD

**Issue by craigatgoogle** [jenkinsci/google-kubernetes-engine-plugin#16]
* Migrate Issues from Jira to GitHub: https://issues.jenkins-ci.org/browse/JENKINS-56253?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20google-kubernetes-engine-plugin
* Leave a comment on each issue with a link to the corresponding GitHub issue, and then close the issue in Jira.
* Create a guide-post issue template in Jira directing folks to GitHub issues
* Migrate the docs from the Jenkins Wiki to GitHub MD: https://wiki.jenkins.io/display/JENKINS/Google+Kubernetes+Engine+Plugin
* Leave a guide-post link from the wiki pointing to the GitHub docs.

**Comment by stephenashank** [comment]
The Jenkins Wiki page now points to the main page, which has installation instructions and other key information, as well as a link to the docs from #26.

All issues on JIRA that were resolved by changes included in 0.2.0 are marked as resolved. Issues that were not completed have been migrated here and closed on JIRA with a link to the corresponding github issue.

**Comment by stephenashank** [comment]
The Jenkins wiki points to the README which contains instructions for using github issues. It isn't possible to create a guidepost template, so the README instructions are sufficient and I consider this done.

**Comment by craigatgoogle** [comment]
Great work! Thanks for taking care of this.
