### ISSUE TITLE
[Feature]: Deployment verification

### ISSUE THREAD

**Issue by stephenashank** [jenkinsci/google-kubernetes-engine-plugin#23]
This issue tracks the work involved in adding logic to verify successful deployment of manifest configurations.

**Comment by johnlabarge** [comment]
I'm working on this one. You can assign it to me.

**Comment by stephenashank** [comment]
When I try to assign the issue you don't show up in the list of possible assignees.

**Comment by craigatgoogle** [comment]
@johnlabarge sent you a collaborator invite. Once you click the accept link we can assign this issue to you.

**Comment by johnlabarge** [comment]
Done.  Very much WIP: https://github.com/johnlabarge/google-kubernetes-engine-plugin/tree/develop

**Comment by craigatgoogle** [comment]
@johnlabarge if there's a way we can take a look at some incremental PRs that would be preferred over having to review a single giant PR when it comes time to integrate your changes.

**Comment by craigatgoogle** [comment]
Implemented: https://github.com/jenkinsci/google-kubernetes-engine-plugin/pull/33
