### ISSUE TITLE
Get a NullPointerException when trying to deploy. Seems to fail when attempting to generate kubeconfig.

### ISSUE THREAD

**Issue by MatthewAry** [jenkinsci/google-kubernetes-engine-plugin#37]
This is the error we see in builds.
```
java.lang.NullPointerException: null value
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:139)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:178)
	at com.google.jenkins.plugins.k8sengine.KubeConfig.user(KubeConfig.java:193)
	at com.google.jenkins.plugins.k8sengine.KubeConfig.fromCluster(KubeConfig.java:153)
	at com.google.jenkins.plugins.k8sengine.KubernetesEngineBuilder.perform(KubernetesEngineBuilder.java:181)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.build(MavenModuleSetBuild.java:945)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:896)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1816)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```
We are using a service account with sufficient privileges (we even tried setting it to project owner). Project ID, Zone, Cluster, and manifest have been specified.

Manifest Path: /var/lib/jenkins/files/manifest.yml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - env:
        - name: DB_USER_NAME
          valueFrom:
            secretKeyRef:
              key: DB_USER_NAME
              name: credentials
        - name: DB_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_USER_PASSWORD
              name: credentials
        - name: DB_HOST_NAME
          valueFrom:
            secretKeyRef:
              key: DB_HOST_NAME
              name: credentials
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: credentials
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: BUCKET_NAME
              name: credentials
        - name: PROD_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: PROD_BUCKET_NAME
              name: credentials
        - name: SERVICE_ACCOUNT_KEY
          value: /var/secrets/google/key.json
        image: gcr.io/<PROJECT_ID>/app_v1:latest
        imagePullPolicy: Always
        name: app-v1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/secrets/google
          name: service-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: service-key
        secret:
          defaultMode: 420
          secretName: bucket-key
```
I'm not sure what the issue is. Please advise.

Thank you in advance!

**Comment by stephenashank** [comment]
I think the issue is most likely with the path that you are using for the Manifest. If you put an "execute shell" build step before this one with just
```
pwd
```
what do you see? The value you enter for the path should be relative to this path.

**Comment by stephenashank** [comment]
@MatthewAry Looked into this a bit deeper and you can ignore my comment above.

Based on the failure at line 193 of KubeConfig.java, and the fact that cluster isn't null, this might be due to the way that your cluster is configured because the Client Certificate for your cluster appears to be null. Enabling legacy authorization may fix this. Apart from creating the cluster, have you followed the steps here? 

https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/develop/docs/Home.md#configure-gke-cluster

**Comment by MatthewAry** [comment]
I assumed that I would be able to use an absolute path (and relative paths). However, after examining the code references behind the build error message, I couldn't determine what I was doing wrong. Based on the output of `pwd` I changed the path to simply `manifest.yml` and ran the build again. However I got the same error as before and the deployment failed.

Our Jenkins instance is running in GCE not GKE.

**Comment by MatthewAry** [comment]
@stephenashank Using Cloud Shell I performed the steps listed under **Configure GKE Cluster** and **Configure Kubernetes Cluster Permissions** before reaching out to you.

**Comment by craigatgoogle** [comment]
@MatthewAry this usually shows up when the GCP SA doesn't have the proper permissions for the GKE API. Could you please verify your SA has the role: roles/container.admin

**Comment by MatthewAry** [comment]
Legacy Authorization is enabled. I ran
```
export SA_EMAIL=$(gcloud iam service-accounts list --filter="name:jenkins" --format='value(email)')
gcloud projects add-iam-policy-binding --member serviceAccount:$SA_EMAIL --role roles/container.admin $PROJECT
```
and I checked to see if the `$PROJECT` variable was set properly. The console output indicated that the service account has the permission necessary. Jenkins is just beginning to containerize my application in it's build process. I will let you know what the result it.

**Comment by MatthewAry** [comment]
The build failed again with the same error. Please advise as to what I should do next.

**Comment by stephenashank** [comment]
In cloud shell, try running the following command with the appropriate values for your project filled in:
```
gcloud projects get-iam-policy <PROJECT_ID>  \
--flatten="bindings[].members" \
--format='table(bindings.role)' \
--filter="bindings.members:<SERVICE_ACCOUNT_NAME>"
```

At a minimum you should see these
```
roles/compute.instanceAdmin.v1
roles/container.admin
roles/container.clusterAdmin
roles/iam.serviceAccountUser
```

**Comment by stephenashank** [comment]
@MatthewAry Try the above and add any missing roles to your account using the gcloud `add-iam-policy-binding` command you used above.

**Comment by MatthewAry** [comment]
I was missing the following roles
```
roles/compute.networkViewer
roles/container.clusterAdmin
roles/iam.serviceAccountUser
```
I have added the roles to the SA. My build is in progress. I will update you on the result.

**Comment by MatthewAry** [comment]
Failed again.
```
ERROR: Build step failed with exception
java.lang.NullPointerException: null value
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:139)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:178)
	at com.google.jenkins.plugins.k8sengine.KubeConfig.user(KubeConfig.java:193)
	at com.google.jenkins.plugins.k8sengine.KubeConfig.fromCluster(KubeConfig.java:153)
	at com.google.jenkins.plugins.k8sengine.KubernetesEngineBuilder.perform(KubernetesEngineBuilder.java:181)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.build(MavenModuleSetBuild.java:945)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:896)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1816)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Google Kubernetes Engine' marked build as failure
```

**Comment by stephenashank** [comment]
@MatthewAry Try running this:
```
gcloud container clusters describe $CLUSTER --zone=$ZONE
```

In that output under `masterAuth` do you see values for `clientCertificate` and `clientKey`? If those are blank or not present, then that's a problem.

If you could actually provide these next values I'd appreciate it. My values are there for reference:
```
masterVersion: 1.11.7-gke.12
legacyAbac:
    enabled: true
```

**Comment by MatthewAry** [comment]
@stephenashank I can confirm that there is a `clusterCaCertificate` under `masterAuth` and has a value.

Here is the information you requested.
```
currentMasterVersion: 1.11.7-gke.12
legacyAbac:
  enabled: true
```
I could not find a `masterVersion` value in the output so I provided what I saw that seemed comparable.

**Comment by stephenashank** [comment]
@MatthewAry, Just to clarify, are you saying that your `masterAuth` only has `clusterCaCertificate`?
You should also have `clientCertificate` and `clientKey`, as well as `username` and `password`.

Something like this (with the values redacted):
```
masterAuth:
    clientCertificate: ...
    clientKey: ...
    clusterCaCertificate: ...
    password: ...
    username: ...
```

Also, that should be `currentMasterVersion`, so those two values look good.

**Comment by MatthewAry** [comment]
Under `masterAuth`, I only have `clusterCaCertificate` I do not have `clientCertificate`, `clientKey`, or `username` and `password`. I'm not exactly sure what I would need to do in order to add those.

**Comment by stephenashank** [comment]
They should be created for you when the plugin runs. Now that you've added the roles, did you follow the rest of the steps in the iam credentials section when adding the service account credentials for use with the plugin? https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/develop/docs/Home.md#iam-credentials

**Comment by MatthewAry** [comment]
First off, I really appreciate the help!

I'm using an existing service account. I assume that me exporting and adding new `key.json` file won't make a difference. If the credentials are supposed to be generated on run, then I would expect it to have worked by now.

To summarize what I've done so far...
- I've made sure that my service account has the requisite roles.
- I've attempted to build and deploy again but it failed.
- I've checked to see if there are expected values in `masterAuth` and discovered that there are missing values.
- I suppose I'll try executing the build again since it seems that all the requirements that you've assisted me with should be satisfied. (However, I do recall that I did set the service account level to project owner previously to try to get this to work and it still failed)

Just to be safe I'll create a new key.json file and import it into Jenkins. Then I'll update the project and try again.

I'll let you know what happens.

Thanks!

**Comment by stephenashank** [comment]
My pleasure!

Using a new service account shouldn't be required, although I think running the command in step 3 of those instructions in order to obtain a key might be. Looking forward to what the results are.

**Comment by MatthewAry** [comment]
The build is running. Is there a difference between getting the service account key from Google Cloud Console and from gcloud cli? I got my service account key from the web interface.

**Comment by stephenashank** [comment]
I don't think there should be any difference as long as the key is tied to the service account.

**Comment by MatthewAry** [comment]
That's what I thought. I'm sorry it took so long. The jenkins instance had run out of space, I'm going to have to work on making it clean up after itself a bit better.

Aaaannnd.... It failed again.

**Comment by stephenashank** [comment]
Ah, then definitely try using that command instead of the web UI. And I would create a new Google Service Account credentials and reconfigure the build to use that, just to be sure.

**Comment by MatthewAry** [comment]
Okay, I created the account by following https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/develop/docs/Home.md#iam-credentials exactly. I added the service account to Jenkins and applied it to the GKE Deploy step. I ran the build and it failed with the same error again.

**Comment by MatthewAry** [comment]
Since we have eliminated many different possibilities, is there anything else that I can provide you with which could help further track down the problem? Perhaps I could install a variant of the plugin that prints some desk-checks?

**Comment by stephenashank** [comment]
I've looked at this a bit more, and what I'm going to try reproducing is the current state of your cluster, with missing certificates.

Based on where this happens in the perform step of the builder ([here](https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/a6fea015c63adeaa283fbd2b1c891345e64d8bce/src/main/java/com/google/jenkins/plugins/k8sengine/KubernetesEngineBuilder.java#L181)), I think these need to be defined before retrieving the cluster.

I'll let you know how that goes.

**Comment by stephenashank** [comment]
In the process of creating a new cluster, I found that the cluster immediately had the proper certificate/credentials. I don't know how to find this property through the cli, but in the GKE section of Cloud Console, under clusters, click on the cluster that you're deploying to here. Near the top of that list of properties for the cluster you should see `clientCertificate    enabled`. If not, I'm looking into how to enable this on an already existing cluster. And if it is enabled then there's something else wrong here

**Comment by MatthewAry** [comment]
Client Certificate is Disabled. For further explanation, I've been using the "Your first cluster" GKE template since we are doing development on basic cluster integration and deployment processes.
![screenshot-console cloud google com-2019 03 26-13-52-42](https://user-images.githubusercontent.com/157217/55029006-a6b13780-4fce-11e9-8fac-e3bbccb98f17.png)

**Comment by stephenashank** [comment]
Unfortunately I think this property is baked into the cluster after creation. If you create a new cluster with Client Certificate enabled, then this should work. Can you send me a link to that template? 

If you follow all of the steps in the [tutorial](https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/develop/docs/Home.md#configure-gke-cluster) for the *Configure GKE Cluster* and *Configure Kubernetes Cluster Permissions* sections, then this new cluster (with the current kubernetes cluster version) will have the required client certificate and you can simply switch to this new cluster in your existing build configuration in Jenkins.

For clusters with version 1.11 and below, if you are creating through gcloud then make sure that the command you use to create the cluster does not include `--no-issue-client-certificate`.

For clusters with version 1.12 and above created through gcloud, you will need to explicitly use the flag `--issue-client-certificate` as this won't be enabled by default.

**Comment by MatthewAry** [comment]
I can't really send you a link but here is a screen shot.
<img width="383" alt="Screen Shot 2019-03-26 at 2 08 59 PM" src="https://user-images.githubusercontent.com/157217/55029924-e24d0100-4fd0-11e9-8ff0-bdfb84b7ced6.png">

I'll work on creating a new cluster using the instructions you have provided. I'll let you know how it goes.

**Comment by MatthewAry** [comment]
Just FYI I saw this when making a new cluster.
<img width="436" alt="Screen Shot 2019-03-26 at 2 32 22 PM" src="https://user-images.githubusercontent.com/157217/55031352-09590200-4fd4-11e9-887b-6370f289f2e3.png">

**Comment by stephenashank** [comment]
Oh that template, thanks.

Yes, I'm going to be updating the documentation and will make sure that the client certificate issuance being required is emphasized. In the future we will be able to remove this requirement and that is being tracked through #22, which depends on a future update to Kubernetes.

**Comment by MatthewAry** [comment]
I think I got it working. I'm not getting errors and I can delete a deployment and then run the process to deploy on Jenkins and see a new deployment get created.

**Comment by stephenashank** [comment]
Great! Let me know if anything else is needed here or if I can close out this issue.

**Comment by MatthewAry** [comment]
I think that's it! It looks like everything is working like it should. Thanks so much for your help.
