### ISSUE TITLE
Move usage docs to main README

### ISSUE THREAD

**Issue by viglesiasce** [jenkinsci/google-kubernetes-engine-plugin#59]
It can be easy to miss the doc link on the main page. We should inline the usage docs in the README to provide users with a full idea of how the plugin works as soon as they land on the repo.

**Comment by stephenashank** [comment]
Resolved with https://github.com/jenkinsci/google-kubernetes-engine-plugin/commit/bf08adc3380de820eccfea835bfd646f21e4b60b
