### ISSUE TITLE
"Verify Deployments" help pop up should show info about what it will do

### ISSUE THREAD

**Issue by viglesiasce** [jenkinsci/google-kubernetes-engine-plugin#62]
When looking to enable "Verify Deployments", users are likely to want to know what actions will be performed to verify the deployments. We should spell out the verification procedure to avoid confusion.

**Comment by johnlabarge** [comment]
Are you thinking of this help statement "Check this to verify the availability of a new deployment as specified in the Kubernetes manifest." ?

**Comment by viglesiasce** [comment]
Yep that one. We should add info about what we are actually doing to validate.

**Comment by johnlabarge** [comment]
Would something like: "Check this to verify that the minimum number of replicas for the deployments specified in the Kuberenetes manifest(s) become available. " ?

**Comment by viglesiasce** [comment]
Yeah that sounds about right. Maybe add something that we are polling the
deployment state to get that info?

**Comment by johnlabarge** [comment]
@viglesiasce  @stephenashank  this should be resolved in develop, per above merge.
