### ISSUE TITLE
Allow explicit configuration of namespace as part of build step

### ISSUE THREAD

**Issue by viglesiasce** [jenkinsci/google-kubernetes-engine-plugin#64]
The namespace should be configurable from the build step to allow overrides. We will likely want to have a check box that allows "Deploy to namespace" and then has a text field where the namespace can be entered. By default it would use the default namespace or the one listed in the manifest.

**Comment by stephenashank** [comment]
https://github.com/jenkinsci/google-kubernetes-engine-plugin/pull/66
