### ISSUE TITLE
Set the namespace in the context config so that service account namespace isnt picked up

### ISSUE THREAD

**Issue by viglesiasce** [jenkinsci/google-kubernetes-engine-plugin#65]
When running the agent inside of Kubernetes, the namespace of the agent pod is being interpreted as the namespace to deploy to in the target cluster because kubectl is picking up the namespace from the service account's projected metadata in the filesystem (`/run/secrets/kubernetes.io/serviceaccount/namespace`).

**Comment by rachely3n** [comment]
Let's close this issue when we release #66.

**Comment by stephenashank** [comment]
Thanks for the reminder. #66 was released with `0.5.0`, so I'm going to close and comment.
