### ISSUE TITLE
User "client" cannot get deployments.extensions

### ISSUE THREAD

**Issue by mstypinski** [jenkinsci/google-kubernetes-engine-plugin#77]
After setting up enviroment in Jenkins, the worker isn't able to perform actions on cluster cause it is using user "client"
Error below:
`deployments.extensions "vutp-django" is forbidden: User "client" cannot get deployments.extensions in the namespace "default"`

**Comment by stephenashank** [comment]
Hi @mstypinski was your issue resolved?

**Comment by mstypinski** [comment]
Actually I did not notice that plugin does only support legacy authentication. This way the problem has been omitted
