### ISSUE TITLE
GKE credentials are not shown

### ISSUE THREAD

**Issue by GolanTrevize10** [jenkinsci/google-kubernetes-engine-plugin#79]
Hi, we are using GKE plugin version 0.6 and credentials plugin 2.1.18

User tries to create a new job and adds the Deploy in GKE build step. He creates new credential of type "Google service account from private key". After creating the credential the user is unable to see it in the selection box. He does not even see the none option. However, admin users (meaning user with full permissions) can see the credential in the box. If the user is granted with admin permissions then he can also see the credential.

**Comment by rachely3n** [comment]
What permissions does your Google service account currently have?

**Comment by MartinHajducik** [comment]
Hi , 

includedPermissions:
- container.apiServices.get
- container.apiServices.list
- container.clusters.get
- container.clusters.getCredentials
- container.clusters.list
- resourcemanager.projects.get

Is this really related to service user acocunt ? This seems like Jenkins is somehow unable to show defined credentials in Service Account Credentials select box.

**Comment by GolanTrevize10** [comment]
Hi, thanks for the answer. When I mentioned permissions I mean Jenkins permissions. I don't think Google service account permissions have something to do. These are the permissions the user has in the Jenkins folder (last row)

![image](https://user-images.githubusercontent.com/25170481/58555442-c6a4e780-8219-11e9-827b-25c47f0bfe2f.png)

**Comment by stephenashank** [comment]
https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/bd42d72d6063c6464dec9c84ea25669d57dc44ab/src/main/java/com/google/jenkins/plugins/k8sengine/KubernetesEngineBuilder.java#L371

As you can see here the permission we currently check for is Item.Configure, which I think is carried over from something similar in the GCE plugin, and can be changed to something more permissive like Credentials-View. Also looks like we don't provide a none option in the dropdown in that case either, so thanks for pointing that out.

**Comment by GolanTrevize10** [comment]
Thanks for finding the issue. Are you planning then to change it?

**Comment by rachely3n** [comment]
I'll try to get a change out today.

**Comment by GolanTrevize10** [comment]
Thanks

**Comment by GolanTrevize10** [comment]
Hi, by when can we expect a solution for this problem?

**Comment by pavenova** [comment]
Hello, kindly please any update on this issue? 
FYI @MartinHajducik  

I just checked, and there is still not plugin update available,
thanks for answer

**Comment by MartinHajducik** [comment]
Hi,

Do we have any update here ?

**Comment by stephenashank** [comment]
I will cut a release of the plugin today, after which it will arrive in the update center.

**Comment by stephenashank** [comment]
@GolanTrevize10 @pavenova @MartinHajducik  Release 0.6.1 has been submitted with the fix, look for it in the update center soon.

**Comment by MartinHajducik** [comment]
Are we doing something wrong ? We are now using  release 0.6.1 . When we add credentials inside of "Deploy to Kubernetes Engine build step" , it is added in project credentials store, but cannot be listed . 

![image](https://user-images.githubusercontent.com/41745906/59088107-c8039d80-8906-11e9-992b-1b5efcbaec1a.png)

Only credentails under located under global store are visible in select menu

![image](https://user-images.githubusercontent.com/41745906/59088191-15800a80-8907-11e9-8f58-652b38c68ead.png)

**Comment by stephenashank** [comment]
Hi, @MartinHajducik, the use of the global domain is intended at the moment. See [IAM Credentials](https://github.com/jenkinsci/google-kubernetes-engine-plugin/blob/develop/docs/Home.md#iam-credentials) for the instructions we provide on creating credentials. 

Can you explain a bit more about how you added the credentials to the project credentials store? I am able to add global credentials from that build step, but have not configured other domains.

**Comment by GolanTrevize10** [comment]
Hi he means the folder credentials store

**Comment by craigdbarber** [comment]
Hi @MartinHajducik I wanted to follow up on this to make sure you're able to get things working with the latest release (0.6.1). Please let me know. Thanks.
