### ISSUE TITLE
[Feature] Blue/Green Deployment

### ISSUE THREAD

**Issue by abdidarmawan007** [jenkinsci/google-kubernetes-engine-plugin#92]
Need fiture support blue/green deployment

**Comment by craigdbarber** [comment]
Hi @abdidarmawan007 thanks for the suggestion. Blue/Green deployment is beyond the scope of this plugin, however this plugin does provide a primitive which could be used in this scenario. I'd suggest taking a look at this article published by CloudBees on the topic: https://www.cloudbees.com/blog/blue-green-deployments-jenkins-and-blue-green-command
